export const GET_TODOS_REQUEST = "GET_TODOS_REQUEST";
export const GET_TODOS_SUCCESS = "GET_TODOS_SUCCESS";
export const GET_TODOS_FAILURE = "GET_TODOS_FAILURE";

export const CREATE_TODOS_REQUEST = "CREATE_TODOS_REQUEST";
export const CREATE_TODOS_SUCCESS = "CREATE_TODOS_SUCCESS";
export const CREATE_TODOS_FAILURE = "CREATE_TODOS_FAILURE";

export const UPDATE_TODOS_REQUEST = "UPDATE_TODOS_REQUEST";
export const UPDATE_TODOS_SUCCESS = "UPDATE_TODOS_SUCCESS";
export const UPDATE_TODOS_FAILURE = "UPDATE_TODOS_FAILURE";

export const DELETE_TODOS_REQUEST = "DELETE_TODOS_REQUEST";
export const DELETE_TODOS_SUCCESS = "DELETE_TODOS_SUCCESS";
export const DELETE_TODOS_FAILURE = "DELETE_TODOS_FAILURE";

export const UPDATE_TODO_STATUS_REQUEST = "UPDATE_TODO_STATUS_REQUEST";
export const UPDATE_TODO_STATUS_SUCCESS = "UPDATE_TODO_STATUS_SUCCESS";
export const UPDATE_TODO_STATUS_FAILURE = "UPDATE_TODO_STATUS_FAILURE";
